name: tictactoe
description: "Tic Tac Toe game for Betclic recruitment task"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  audioplayers: ^6.5.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_physics: ^0.2.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  gaimon: ^1.4.1
  go_router: ^17.0.0
  hooks_riverpod: ^3.0.3
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.6.2
  riverpod_annotation: ^3.0.3
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  simple_animations: ^5.2.0

dev_dependencies:
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta-Regular.otf
          weight: 300
        - asset: assets/fonts/Averta-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Averta-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Averta-Bold.otf
          weight: 700
        - asset: assets/fonts/Averta-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Averta-Black.otf
          weight: 900